app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:5173}
spring.cloud.gateway.server.webmvc.routes[0].id=coachassist-admin-api
spring.cloud.gateway.server.webmvc.routes[0].uri=${ADMIN_SERVICE_URL:https://admin-ygw5.onrender.com}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/admin/**
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=RemoveRequestHeader=Accept-Encoding
spring.cloud.gateway.server.webmvc.routes[1].id=coachassist-api
spring.cloud.gateway.server.webmvc.routes[1].uri=${COACHING_SERVICE_URL:https://coaching-jiru.onrender.com}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.server.webmvc.routes[1].filters[1]=RemoveRequestHeader=Accept-Encoding
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}
management.endpoints.web.exposure.include=health
eureka.client.service-url.defaultZone=${EUREKA_URL:https://eureka-server-cpd6.onrender.com}
