# System Application Name
spring.application.name=api-gateway

# CORS
app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:3000}

# Gateway MVC CORS
spring.cloud.gateway.server.webmvc.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOrigins=${FRONTEND_ORIGIN:http://localhost:3000}
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].exposedHeaders=Authorization
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].maxAge=3600

# Eureka Client Configuration (Fixes NullPointerException)
eureka.client.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_URL:https://eureka-server-cpd6.onrender.com/eureka/}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true

# Actuator & Refresh Management
management.endpoints.web.exposure.include=health,refresh

# Route 0: Admin API
spring.cloud.gateway.server.webmvc.routes[0].id=coachassist-admin-api
spring.cloud.gateway.server.webmvc.routes[0].uri=${ADMIN_SERVICE_URL:https://admin-ygw5.onrender.com}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/admin/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0].name=RemoveRequestHeader
spring.cloud.gateway.server.webmvc.routes[0].filters[0].args.name=Accept-Encoding

# Route 1: Coaching API
spring.cloud.gateway.server.webmvc.routes[1].id=coachassist-api
spring.cloud.gateway.server.webmvc.routes[1].uri=${COACHING_SERVICE_URL:https://coaching-jiru.onrender.com}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/coaching/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0].name=RemoveRequestHeader
spring.cloud.gateway.server.webmvc.routes[1].filters[0].args.name=Accept-Encoding
