
jwt.secret=${JWT_SECRET:CoachAssistAyushFaizan9865dsufef67cwvsquwdbfcweygw+452986v}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.student-service-url=${STUDENT_SERVICE_URL:https://student-gzyr.onrender.com}
app.parent-service-url=${PARENT_SERVICE_URL:https://coachassistt-kdpv.onrender.com}
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-dark-smoke-b5k6n479-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_yVm4zuBjkWD9}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
management.endpoints.web.exposure.include=health
